New donation reading pages
GamesDoneQuick/donation-tracker pull request #527
Opened 2023-04-09 15:27 UTC by faultyserver

# Contributing to the Donation Tracker

First of all, thank you for taking the time to contribute!

Please fill out the template below and check the following boxes:

- [ ] I've added tests or modified existing tests for the change.
- [x] I've humanly end-to-end tested the change by running an instance of the tracker.

### Description of the Change

This introduces a new, revamped Read Donations page to match the existing new Process Donations page from last year. The new page focuses on the feedback we've received from hosts over the past few years, wanting to have more options for marking and grouping donations to be read at certain times. The list of general features includes:

- Live socket updating, so new donations will immediately show up as they are processed. The refresh button is still there for safety, but hosts should never really have to refresh the page.
- Local tagging, letting hosts create any number of groups they'd like and managing the donations within those groups as they wish. Tags show up on all views and in the sidebar as selectable filters. Tags and groups are specific to each device using the site.
- Permanent on the sidebar for different types of donations. Anonymous and No Comment are the only two that really exist right now, but that leads to:
- Pinned donations are now the way of "sharing" donations across hosts. Tags are only saved locally in each browser (using `localStorage`), but pins are an actual state on the donation, so they can be used to communicate a specific set of donations across multiple hosts and devices.
- Highly requested dark theme, since it comes for free with the design system.

Other features that are still to come after this initial merge include:
- Drag and drop for donations within groups, so hosts can have things ordered exactly how they wish.
- Relative timestamps to make the donation time easier to glance at.
- A list of recently-read donations to be able to undo or go back on donations that are accidentally marked wrong.
- Keyword highlighting similar to the processing pages.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/783733/230781278-e85e8ccf-1866-4022-b3f0-ac9046e769f1.png">

### Verification Process

What process did you follow to verify that the change has not introduced any regressions? Describe the actions you took apart from writing tests, such as running a local instance of the tracker. (What buttons did you press, etc.)

2023-04-09 15:34 UTC, faultyserver commented on bundles/admin/processing/DonationsStore.tsx
This splits out `DonationsStore` from the `ProcessingStore` so that donations are held in a single place and easily usable across pages. Then `ProcessingStore` becomes strictly about the information for processing, like the mode, partitions, and keyword searching.

2023-04-17 03:06 UTC, uraniumanchor requested changes

2023-04-17 03:06 UTC, uraniumanchor commented on tracker/api/views/donations.py
> +            .all()
Does this `all` actually do something here that I'm forgetting?

2023-04-17 03:06 UTC, uraniumanchor commented on tracker/api/views/donations.py
> +        donations = Donation.objects.filter(pk__in=donation_ids).all()
Same with this one...

2023-04-17 03:29 UTC, faultyserver commented on tracker/api/views/donations.py
> +            .all()
Nope, I just don't 100% understand django's ORM. Apparently this just returns a copy of the queryset for anything other than `objects.all()`, so it does nothing here.

2023-04-17 04:07 UTC, uraniumanchor requested changes

2023-04-17 04:07 UTC, uraniumanchor commented on tracker/api/views/donations.py
> +        up to a maximum of 200 donations.
Missed this before, or maybe a merge ate it: `TRACKER_PAGINATION_LIMIT`.

2023-04-17 04:07 UTC, uraniumanchor commented on tracker/api/views/donations.py
> +        if len(donation_ids) > 200:
Missed this before, or maybe a merge ate it: TRACKER_PAGINATION_LIMIT.

2023-04-17 04:09 UTC, faultyserver commented on tracker/api/views/donations.py
> +        up to a maximum of 200 donations.
i think this one was added and the other was eaten. fixed now.

2023-04-17 04:23 UTC, uraniumanchor submitted a review, later dismissed

2023-04-17 04:50 UTC, merged