Enable viewing/adding moderator comments from processing pages
GamesDoneQuick/donation-tracker pull request #541
Opened 2023-04-19 18:40 UTC by faultyserver

# Contributing to the Donation Tracker

First of all, thank you for taking the time to contribute!

Please fill out the template below and check the following boxes:

- [x] I've added tests or modified existing tests for the change.
- [x] I've humanly end-to-end tested the change by running an instance of the tracker.

### Description of the Change

This adds the ability for processors and readers to both view and edit moderator comments on donations. The UI on each page is slightly different, mainly just for simplicity at this point. Once things are refactor and deduped, it will be more consistent.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/783733/233169535-7a67d203-7a39-402c-8fb4-a93a302f1ddc.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/783733/233169578-8062dafc-f189-4f0b-a69d-db77698a3ac4.png">
<img width="598" alt="image" src="https://user-images.githubusercontent.com/783733/233169643-cf0bb9f8-eb40-465d-ab30-54dbaf1959f4.png">

### Verification Process

Tested that adding mod comments on donations works from each page, and that live updates are sent including the comments to all processing consumers.

2023-04-19 18:43 UTC, faultyserver commented on tracker/api/serializers.py
> +
Eventually I think this could/should become a base class for our serializers so that they all can work with permissions. Maybe with a better syntax for using it as well.

2023-04-19 18:43 UTC, faultyserver commented on tracker/consumers/processing.py
> +                'donation': _serialize_donation(donation),
This is the main reason I went with this approach for serialization with permissions directly rather than a Request/User object. Channels don't have the concept of a request, and DRF's model for getting a user in the serializer is to go through the request by way of a `context` property.

Just working on permissions directly means there's no indirection, and serialization works fully outside of a request context.

2023-04-21 08:40 UTC, uraniumanchor requested changes
Just a couple minor things.

2023-04-21 08:40 UTC, uraniumanchor commented on tests/apiv2/test_serializers.py
> +            'bidstate',
`bidstate` can be removed, it's been meaningless for at least seven years. It's been on my list of things to pitch for a while now.

2023-04-21 08:40 UTC, uraniumanchor commented on tracker/api/views/donations.py
> +            return Response({'error': '`comment` was not be provided'}, status=422)
Typo?

2023-04-21 23:05 UTC, uraniumanchor approved these changes
Once the conflicts are fixed this looks good.

2023-04-22 01:15 UTC, merged