Channels 4.1.0
GamesDoneQuick/donation-tracker pull request #713
Opened 2024-09-04 17:42 UTC by pyrox0

# Contributing to the Donation Tracker

First of all, thank you for taking the time to contribute!

Please fill out the template below and check the following boxes:

- [x] I've added tests or modified existing tests for the change.
- [x] I've humanly end-to-end tested the change by running an instance of the tracker.

### Issue from Pivotal Tracker

Link to the issue from the [public Pivotal Tracker](https://www.pivotaltracker.com/n/projects/1521291) that your change addresses. (Expand the story and click the link icon to copy the link to your clipboard.)
N/A

### Description of the Change

If fixing a bug, please describe the bug and provide reproduction steps.

If adding a feature or changing functionality, please describe the change in a way that makes it easy to understand the design of the change. When applicable, screenshots are very useful to help us understand changes.

If there are possible side effects of negative impacts of the code change, list them here.

* `channels` dependency updated
* `daphne` dependency added to `tests/requirements.txt` as well as a `development` extra for when using the development setup instructions
* README updated to include daphne installation/setup
* README was also updated to include migration and superuser creation commands in development setup(as needed to actually use the tracker) and removed mentions of the websocket test page as it no longer exists.
* `tests/routing.py` updated to include an explicit `http` handler as implicit HTTP routing was removed in Channels 4.0.
* `tests/settings.py` had `daphne` added to INSTALLED_APPS. Has to be at the top so it can register its own `runserver` command before Django.

This is technically  a breaking change, but the changes are minimal, and also removes calls to the `cgi` stdlib module(from inside channels) that will be [removed in python 3.13](https://docs.python.org/3.13/whatsnew/3.13.html#whatsnew313-pep594). If your application is already using explicit HTTP routing, then there are no fixes needed since all 4.0 does is enforce the need for explicit HTTP routing.

### Verification Process

What process did you follow to verify that the change has not introduced any regressions? Describe the actions you took apart from writing tests, such as running a local instance of the tracker. (What buttons did you press, etc.)

I ran the tests in the repo, as well as went through my setup steps as detailed in the updated README to create a new development environment, to ensure the steps work properly.

2024-09-04 19:51 UTC, uraniumanchor requested changes
Looks good other than one small tweak since you're editing that section anyway.

2024-09-04 19:51 UTC, uraniumanchor commented on README.md
> +If the page loads but the pings don't work, Channels isn't set up correctly. The
Since you're changing this anyway, maybe this is either where the diagnostic page should be mentioned, or at least referenced again. This is definitely a leftover from before that page existed.

2024-09-04 21:14 UTC, pyrox0 commented on README.md
> +If the page loads but the pings don't work, Channels isn't set up correctly. The
I'll update to link the diagnostic page instead, good idea!

2024-09-05 16:02 UTC, uraniumanchor approved these changes

2024-09-05 16:10 UTC, merged